[project]
name = "duckdb-dbt-challenge"
version = "0.1.0"
description = "A challenge to demonstrate my skills as Junior Data Engineer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-core>=1.8.8",
    "dbt-duckdb>=1.9.0",
    "duckdb>=1.1.3",
    "ruff>=0.7.4",
]
