version: 2

models:
  - name: stg_yellow_tripdata__trips
    columns:
      - name: pickup_at
        data_tests:
          - not_null    
      - name: total_amount
        data_tests:
          - not_null          
      - name: time_slot
        data_tests:
          - accepted_values:
              values: ['Morning', 'Afternoon', 'Evening', 'Night']
      - name: pu_location_id
        data_tests:
          - not_null
      - name: vendor_id
        data_tests:
          - not_null
      - name: tip_amount
        data_tests:
          - not_null
      - name: trip_segment
        data_tests:
          - accepted_values:
              values: ['Short', 'Medium', 'Long']
      - name: trip_duration
        data_tests:
          - not_null

            